"use client";

import { useEffect, useState } from "react";
import { Alert, Button, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Divider, Stack, Typography } from "@mui/material";
import PrintOutlinedIcon from "@mui/icons-material/PrintOutlined";
import { extractApiErrorMessage, unwrapApiResponse } from "@/lib/api-client";

type Detail = { receiptNo: string; issuedAt: string; receiverName?: string | null; amount: number; status: string; payment: { paymentNo: string; paymentMethod: string; transactionReference?: string | null; tuitionFee: { feeNo: string; student: { code: string; fullName: string }; class: { name: string }; items: Array<{ itemName: string; amount: number }> } } };
export function ReceiptDetailDialog({ id, onClose }: { id: string; onClose: () => void }) {
  const [data, setData] = useState<Detail | null>(null); const [error, setError] = useState("");
  useEffect(() => { void fetch(`/api/receipts/${id}`).then(async (response) => { if (!response.ok) throw new Error(await extractApiErrorMessage(response, "Không thể tải chi tiết biên lai")); return unwrapApiResponse<Detail>(response); }).then(setData).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Không thể tải chi tiết biên lai")); }, [id]);
  return <Dialog open onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Chi tiết biên lai</DialogTitle><DialogContent>{error && <Alert severity="error">{error}</Alert>}{!data && !error && <Stack alignItems="center" sx={{ py: 4 }}><CircularProgress /></Stack>}{data && <Stack spacing={1.5} sx={{ mt: 1 }}><Typography>Số phiếu: <strong>{data.receiptNo}</strong></Typography><Typography>Payment: {data.payment.paymentNo}</Typography><Typography>Học phí: {data.payment.tuitionFee.feeNo}</Typography><Typography>Học sinh: {data.payment.tuitionFee.student.code} — {data.payment.tuitionFee.student.fullName}</Typography><Typography>Lớp: {data.payment.tuitionFee.class.name}</Typography><Typography>Người nộp: {data.receiverName || "-"}</Typography><Typography>Phương thức: {data.payment.paymentMethod}</Typography><Typography>Ngày thu: {new Date(data.issuedAt).toLocaleString("vi-VN")}</Typography><Divider /><Typography variant="h6">{Number(data.amount).toLocaleString("vi-VN")} VND</Typography><Stack direction={{ xs: "column", sm: "row" }} spacing={1}><Button variant="outlined" href={`/api/tuition-receipts/${id}/pdf`}>Tải PDF</Button><Button variant="contained" startIcon={<PrintOutlinedIcon />} href={`/api/tuition-receipts/${id}/pdf?inline=1`} target="_blank" rel="noopener noreferrer">Mở để in</Button></Stack></Stack>}</DialogContent><DialogActions><Button onClick={onClose}>Đóng</Button></DialogActions></Dialog>;
}
