"use client";

import { useCallback, useEffect, useState } from "react";
import { Alert, Button, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import { extractApiErrorMessage, unwrapApiResponse } from "@/lib/api-client";

type Schedule = { id: string; dayOfWeek: number; startMinute: number; endMinute: number; teacher?: { user?: { fullName?: string | null } | null } | null };
const days = ["Chủ nhật", "Thứ 2", "Thứ 3", "Thứ 4", "Thứ 5", "Thứ 6", "Thứ 7"];
const toMinutes = (value: string) => { const [hour = 0, minute = 0] = value.split(":").map(Number); return hour * 60 + minute; };
const toTime = (value: number) => `${String(Math.floor(value / 60)).padStart(2, "0")}:${String(value % 60).padStart(2, "0")}`;

export function ClassSchedulePanel({ classId, teacherId, teacherName }: { classId: string; teacherId?: string | null; teacherName: string }) {
  const [items, setItems] = useState<Schedule[]>([]); const [day, setDay] = useState(1); const [start, setStart] = useState("08:00"); const [end, setEnd] = useState("10:00"); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const response = await fetch(`/api/schedules?classId=${classId}&pageSize=100`); if (response.ok) setItems((await unwrapApiResponse<{ items: Schedule[] }>(response)).items); else setError(await extractApiErrorMessage(response, "Không thể tải lịch học")); }, [classId]);
  useEffect(() => { void load(); }, [load]);
  async function addSchedule() { if (!teacherId) { setError("Lớp chưa có giáo viên chính"); return; } if (toMinutes(start) >= toMinutes(end)) { setError("Giờ kết thúc phải sau giờ bắt đầu"); return; } setSaving(true); setError(""); const response = await fetch("/api/schedules", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ classId, teacherId, dayOfWeek: day, startMinute: toMinutes(start), endMinute: toMinutes(end) }) }); if (!response.ok) setError(await extractApiErrorMessage(response, "Không thể tạo lịch học")); else await load(); setSaving(false); }
  async function removeSchedule(id: string) { setSaving(true); const response = await fetch(`/api/schedules/${id}`, { method: "DELETE" }); if (!response.ok) setError(await extractApiErrorMessage(response, "Không thể xóa lịch học")); else await load(); setSaving(false); }
  return <Stack spacing={2}><Paper sx={{ p: 2 }}><Stack spacing={2}><Typography>Giáo viên của lớp: <strong>{teacherName || "Chưa phân công"}</strong></Typography><Stack direction={{ xs: "column", md: "row" }} spacing={1}><Select size="small" value={day} onChange={(e) => setDay(Number(e.target.value))}>{days.map((label, index) => <MenuItem key={label} value={index}>{label}</MenuItem>)}</Select><TextField size="small" type="time" label="Bắt đầu" value={start} onChange={(e) => setStart(e.target.value)} InputLabelProps={{ shrink: true }} /><TextField size="small" type="time" label="Kết thúc" value={end} onChange={(e) => setEnd(e.target.value)} InputLabelProps={{ shrink: true }} /><Button variant="contained" onClick={() => void addSchedule()} disabled={saving}>Thêm lịch học</Button></Stack>{error && <Alert severity="error">{error}</Alert>}</Stack></Paper><Paper sx={{ overflow: "auto" }}><Table size="small"><TableHead><TableRow><TableCell>Ngày</TableCell><TableCell>Thời gian</TableCell><TableCell>Giáo viên</TableCell><TableCell /></TableRow></TableHead><TableBody>{items.map((item) => <TableRow key={item.id}><TableCell>{days[item.dayOfWeek]}</TableCell><TableCell>{toTime(item.startMinute)} - {toTime(item.endMinute)}</TableCell><TableCell>{item.teacher?.user?.fullName || teacherName || "-"}</TableCell><TableCell align="right"><Button color="error" size="small" startIcon={<DeleteOutlineIcon />} onClick={() => void removeSchedule(item.id)} disabled={saving}>Xóa</Button></TableCell></TableRow>)}{!items.length && <TableRow><TableCell colSpan={4}><Typography sx={{ p: 3, textAlign: "center" }} color="text.secondary">Lớp chưa có lịch học</Typography></TableCell></TableRow>}</TableBody></Table></Paper></Stack>;
}
