"use client";

import { useCallback, useEffect, useState } from "react";
import { Alert, Button, Chip, Paper, Stack, Tab, Tabs, Table, TableBody, TableCell, TableRow, Typography } from "@mui/material";
import PersonAddAlt1Icon from "@mui/icons-material/PersonAddAlt1";
import Link from "next/link";
import { ClassSchedulePanel } from "./ClassSchedulePanel";
import { StudentSelectDialog, type StudentItem } from "@/components/shared/dialogs/StudentSelectDialog";
import { extractApiErrorMessage, unwrapApiResponse } from "@/lib/api-client";

type ClassData = { id: string; code: string; name: string; tuitionFee: number; totalSessions: number; status: string; startDate?: string | null; endDate?: string | null; teacher?: { user?: { fullName?: string | null } | null } | null; teacherId?: string | null; students?: Array<{ id: string; student: { code: string; fullName: string } }> };
type Fee = { id: string; feeNo: string; finalAmount: number; status: string; student: { code: string; fullName: string } };

const classStatusLabels: Record<string, string> = { ACTIVE: "Hoạt động", DRAFT: "Nháp", COMPLETED: "Hoàn thành", CANCELLED: "Đã hủy" };
const feeStatusLabels: Record<string, string> = { UNPAID: "Chưa thanh toán", OVERDUE: "Quá hạn", PAID: "Đã thanh toán", EXEMPTED: "Miễn học phí", CANCELLED: "Đã hủy" };

export function ClassDetailPanel({ id }: { id: string }) {
  const [classData, setClassData] = useState<ClassData | null>(null); const [fees, setFees] = useState<Fee[]>([]); const [tab, setTab] = useState(0); const [studentDialogOpen, setStudentDialogOpen] = useState(false); const [addingStudent, setAddingStudent] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/classes/${id}`); if (!response.ok) { setError(await extractApiErrorMessage(response, "Không thể tải lớp học")); return; } const data = await unwrapApiResponse<ClassData>(response); setClassData(data); const feeResponse = await fetch(`/api/tuition-fees?classId=${id}&pageSize=200`); if (feeResponse.ok) setFees((await unwrapApiResponse<{ items: Fee[] }>(feeResponse)).items); }, [id]);
  async function addStudent(student: StudentItem) { setAddingStudent(true); setError(""); try { const response = await fetch(`/api/classes/${id}/students`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ studentId: student.id }) }); if (!response.ok) throw new Error(await extractApiErrorMessage(response, "Không thể đăng ký học sinh")); setStudentDialogOpen(false); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể đăng ký học sinh"); } finally { setAddingStudent(false); } }
  useEffect(() => { void load(); }, [load]);
  if (error) return <Alert severity="error">{error}</Alert>; if (!classData) return <Typography>Đang tải lớp học...</Typography>;
  return <Stack spacing={2} width="100%"><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between"><Stack><Typography variant="h5" fontWeight={700}>{classData.code} — {classData.name}</Typography><Typography color="text.secondary">Quản lý thông tin lớp, lịch học, học sinh và học phí trong cùng một nơi</Typography></Stack><Button component={Link} href="/admin/classes" variant="outlined">Quay lại</Button></Stack><Paper><Tabs value={tab} onChange={(_, value) => setTab(value)} variant="scrollable"><Tab label="Thông tin lớp" /><Tab label="Lịch học" /><Tab label="Học phí" /></Tabs></Paper>{error && <Alert severity="error">{error}</Alert>}{tab === 0 && <Paper sx={{ p: 3 }}><Stack direction={{ xs: "column", md: "row" }} spacing={4}><Info label="Giáo viên">{classData.teacher?.user?.fullName || "Chưa phân công"}</Info><Info label="Học phí lớp">{Number(classData.tuitionFee).toLocaleString("vi-VN")} VND</Info><Info label="Số buổi">{classData.totalSessions}</Info><Info label="Trạng thái"><Chip color={classData.status === "ACTIVE" ? "success" : classData.status === "CANCELLED" ? "error" : "default"} label={classStatusLabels[classData.status] || classData.status} /></Info><Info label="Thời gian">{classData.startDate ? new Date(classData.startDate).toLocaleDateString("vi-VN") : "-"} → {classData.endDate ? new Date(classData.endDate).toLocaleDateString("vi-VN") : "-"}</Info></Stack></Paper>}{tab === 1 && <ClassSchedulePanel classId={classData.id} teacherId={classData.teacherId} teacherName={classData.teacher?.user?.fullName || ""} />}{tab === 2 && <Paper sx={{ overflow: "auto" }}><Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ xs: "stretch", sm: "center" }} spacing={1} sx={{ p: 2, borderBottom: 1, borderColor: "divider" }}><Typography variant="h6">Danh sách học phí</Typography><Button variant="contained" startIcon={<PersonAddAlt1Icon />} onClick={() => setStudentDialogOpen(true)} disabled={addingStudent}>{addingStudent ? "Đang thêm..." : "Thêm học sinh"}</Button></Stack><Table><TableBody>{fees.map((fee) => <TableRow key={fee.id}><TableCell>{fee.feeNo}</TableCell><TableCell>{fee.student.code} — {fee.student.fullName}</TableCell><TableCell>{Number(fee.finalAmount).toLocaleString("vi-VN")} VND</TableCell><TableCell><Chip size="small" color={fee.status === "PAID" ? "success" : fee.status === "OVERDUE" ? "error" : "warning"} label={feeStatusLabels[fee.status] || fee.status} /></TableCell></TableRow>)}{!fees.length && <TableRow><TableCell><Typography sx={{ p: 3 }} color="text.secondary">Chưa có học phí</Typography></TableCell></TableRow>}</TableBody></Table></Paper>}{studentDialogOpen && <StudentSelectDialog open onClose={() => setStudentDialogOpen(false)} onSelect={(student) => void addStudent(student)} />}</Stack>;
}

function Info({ label, children }: { label: string; children: React.ReactNode }) { return <Stack minWidth={160}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography>{children}</Typography></Stack>; }
